# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a1c91771153f9b30c4d0bc84c8b341f2b6cee39b74af35afdd4812223696082e0ab38d67f203c83681a002e06c71cceb8cd660de2c0e2605b5059ff68d5f5d

test:
  secret_key_base: 1522ca04596e0522d0b742591229655360f3725effa5f8ed327e5487064fdf8f5cbb132b916b94bee07b9235858ab9f35e1729a4f806816a9ad6b59345c5e8c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
